---
# Helm installation tasks

- name: Check if Helm is already installed
  ansible.builtin.command: helm version
  register: helm_version_check
  changed_when: false
  failed_when: false

- name: Download Helm installation script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'
  when: helm_version_check.rc != 0

- name: Install Helm
  ansible.builtin.command: /tmp/get_helm.sh
  become: true
  when: helm_version_check.rc != 0
  register: helm_install
  changed_when: helm_install.rc == 0

- name: Clean up Helm installation script
  ansible.builtin.file:
    path: /tmp/get_helm.sh
    state: absent
  when: helm_version_check.rc != 0

- name: Add stable Helm repo
  ansible.builtin.command: helm repo add stable https://charts.helm.sh/stable
  register: helm_repo_add
  changed_when: helm_repo_add.rc == 0
  failed_when: false

- name: Update Helm repositories
  ansible.builtin.command: helm repo update
  register: helm_repo_update
  changed_when: helm_repo_update.rc == 0 