---
# Kubernetes master node initialization tasks

- name: Create Kubernetes init configuration
  ansible.builtin.template:
    src: kubeadm-init.yaml.j2
    dest: /tmp/kubeadm-init.yaml
    owner: root
    group: root
    mode: '0600'
  become: true

- name: Initialize Kubernetes cluster with kubeadm
  ansible.builtin.command: kubeadm init --config=/tmp/kubeadm-init.yaml --upload-certs
  become: true
  register: kubeadm_init
  args:
    creates: "{{ kubeconfig_file }}"

- name: Store kubeadm init output
  ansible.builtin.copy:
    content: "{{ kubeadm_init.stdout }}"
    dest: /root/kubeadm-init.log
    mode: '0600'
  become: true
  when: kubeadm_init.changed

- name: Create .kube directory for root
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0700'
  become: true

- name: Copy admin.conf to root's kube config
  ansible.builtin.copy:
    src: "{{ kubeconfig_file }}"
    dest: /root/.kube/config
    remote_src: true
    mode: '0600'
  become: true 