---
# Pod network setup tasks

- name: Check if Calico is already installed
  ansible.builtin.command: kubectl get pods -n kube-system -l k8s-app=calico-node
  register: calico_check
  changed_when: false
  failed_when: false

- name: Download Calico manifest
  ansible.builtin.get_url:
    url: "{{ calico_manifest_url }}"
    dest: /tmp/calico.yaml
    mode: '0644'
  when: calico_check.rc != 0 or calico_check.stdout == ""

- name: Apply Calico manifest
  ansible.builtin.command: kubectl apply -f /tmp/calico.yaml
  register: calico_apply
  changed_when: calico_apply.rc == 0
  when: calico_check.rc != 0 or calico_check.stdout == ""

- name: Wait for Calico pods to be ready
  ansible.builtin.command: kubectl wait --for=condition=Ready pods --all -n kube-system --timeout=300s
  register: calico_wait
  changed_when: false
  retries: 5
  delay: 60
  until: calico_wait.rc == 0
  when: calico_check.rc != 0 or calico_check.stdout == ""

- name: Remove master node taint if present
  ansible.builtin.command: kubectl taint nodes {{ inventory_hostname }} node-role.kubernetes.io/control-plane:NoSchedule-
  register: remove_taint
  changed_when: remove_taint.rc == 0
  failed_when: remove_taint.rc != 0 and "not found" not in remove_taint.stderr
  when: "'no_schedule_on_master' is defined and not no_schedule_on_master | bool" 