---
# Generate join token for worker nodes

- name: Create join token
  ansible.builtin.command: kubeadm token create --print-join-command
  register: kubeadm_join_command
  changed_when: false
  become: true

- name: Save join command to variable
  ansible.builtin.set_fact:
    kubernetes_join_command: "{{ kubeadm_join_command.stdout }}"

- name: Show join command in console
  ansible.builtin.debug:
    msg: "{{ kubernetes_join_command }}"

- name: Store join command for worker nodes
  ansible.builtin.copy:
    content: "{{ kubernetes_join_command }}"
    dest: "{{ playbook_dir }}/../tmp/kubernetes_join_command"
    mode: '0644'
  become: true
  delegate_to: localhost
  run_once: true

- name: Store join command for other hosts
  ansible.builtin.fetch:
    src: /tmp/kubernetes_join_command
    dest: "{{ playbook_dir }}/../tmp/kubernetes_join_command"
    flat: true
  become: true

- name: Clean up temporary join command file
  ansible.builtin.file:
    path: /tmp/kubernetes_join_command
    state: absent
  become: true 