---
# RKE2 service handlers

- name: restart rke2-server
  ansible.builtin.systemd:
    name: rke2-server
    state: restarted
    daemon_reload: true
  listen: "restart rke2 server"

- name: restart rke2-agent
  ansible.builtin.systemd:
    name: rke2-agent
    state: restarted
    daemon_reload: true
  listen: "restart rke2 agent"

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true 