---

- name: Download kustomize
  ansible.builtin.shell: |
    curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
    mv kustomize /usr/local/bin/kustomize
  become: true
  tags: kustomize