---

- name: Install and configure kubernetes openstack cloud controller manager
  ansible.builtin.import_tasks: cloud_controller_manager.yml
  tags: occm

- name: Install octavia ingress controller
  ansible.builtin.import_tasks: octavia_ingress_install.yml
  tags: octavia-ingress-controller

- name: Install helm
  ansible.builtin.import_tasks: install_helm.yml
  tags: helm

- name: Install kustomize
  ansible.builtin.import_tasks: kustomize_install.yml
  tags: kustomize

- name: Install longhorn
  ansible.builtin.import_tasks: longhorn_install.yml
  tags: longhorn