---

- name: Create RKE2 installation directory for workers
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    mode: "0755"
  become: true
  tags: install_rke2
  when: inventory_hostname in groups['workers']

- name: Create RKE2 configuration file for workers
  ansible.builtin.copy:
    content: "{{ rke2_server_config }}"
    dest: /etc/rancher/rke2/config.yaml
    mode: "0644"
  become: true
  tags: install_rke2
  when: inventory_hostname in groups['workers']

- name: Install RKE2 for workers
  ansible.builtin.shell: "curl -sfL https://get.rke2.io | sh -"
  become: true
  tags: install_rke2
  when: inventory_hostname in groups['workers']

- name: Enable and start RKE2 service for workers
  ansible.builtin.systemd:
    name: rke2-agent
    state: started
    enabled: true
  when: inventory_hostname in groups['workers']

- name: Link RKE2 binary to /usr/local/bin for workers
  ansible.builtin.file:
    src: /var/lib/rancher/rke2/bin/{{ item }}
    dest: /usr/local/bin/{{ item }}
    state: link
  with_items:
    - kubectl
    - crictl
    - ctr
    - containerd
    - runc
  become: true
  tags: install_rke2
  when: inventory_hostname in groups['workers']

