---

- name: Create RKE2 installation directory for first master
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    mode: "0755"
  become: true
  tags: install_rke2
  when: inventory_hostname == groups['masters'][0]

- name: Create RKE2 configuration file for first master
  ansible.builtin.copy:
    content: "{{ rke2_server_config }}"
    dest: /etc/rancher/rke2/config.yaml
    mode: "0644"
  become: true
  tags: install_rke2
  when: inventory_hostname == groups['masters'][0]

- name: Install RKE2 for first master
  ansible.builtin.shell: "curl -sfL https://get.rke2.io | sh -"
  become: true
  tags: install_rke2
  when: inventory_hostname == groups['masters'][0]

- name: Enable and start RKE2 service for first master
  ansible.builtin.systemd:
    name: rke2-server
    state: started
    enabled: true
  when: inventory_hostname == groups['masters'][0]

- name: Link RKE2 binary to /usr/local/bin for first master
  ansible.builtin.file:
    src: /var/lib/rancher/rke2/bin/{{ item }}
    dest: /usr/local/bin/{{ item }}
    state: link
  with_items:
    - kubectl
    - crictl
    - ctr
    - containerd
    - runc
  become: true
  tags: install_rke2
  when: inventory_hostname == groups['masters'][0]

- name: Create kubeconfig directory for first master
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: "0755"
  become: true
  tags: install_rke2
  when: inventory_hostname == groups['masters'][0]

- name: Copy RKE2 kubeconfig to ~/.kube/config for first master
  ansible.builtin.copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: ~/.kube/config
    mode: "0644"
    remote_src: yes
  become: true
  tags: install_rke2
  when: inventory_hostname == groups['masters'][0]

- name: Check master node is ready for first master
  ansible.builtin.shell: |
    kubectl --kubeconfig ~/.kube/config get nodes | grep {{ inventory_hostname }} | awk '{print $2}'
  register: node_status
  until: node_status.stdout == "Ready"
  retries: 20
  delay: 15
  failed_when: node_status.rc != 0 or (node_status.retries is defined and node_status.retries == 20)
  become: true
  tags: install_rke2,validate_rke2_token
  when: inventory_hostname == groups['masters'][0]
  
- name: Debug node status for first master
  ansible.builtin.debug:
    msg: "Master node status: {{ node_status.stdout }}"
  when: inventory_hostname == groups['masters'][0]
  tags: validate_rke2_token

- name: Wait for node-token file to be created for first master
  ansible.builtin.wait_for:
    path: /var/lib/rancher/rke2/server/node-token
    state: present
    timeout: 300
  become: true
  when: inventory_hostname == groups['masters'][0]
  tags: validate_rke2_token

- name: Validate node-token file for first master
  ansible.builtin.stat:
    path: /var/lib/rancher/rke2/server/node-token
  register: node_token_stat
  become: true
  when: inventory_hostname == groups['masters'][0]
  tags: validate_rke2_token

- name: Read node token from first master for first master
  ansible.builtin.slurp:
    src: /var/lib/rancher/rke2/server/node-token
  register: node_token_slurp
  become: true
  when: inventory_hostname == groups['masters'][0]
  tags: validate_rke2_token

- name: Register global token variable for first master
  ansible.builtin.set_fact:
    rke2_token: "{{ node_token_slurp['content'] | b64decode | trim }}"
  when: inventory_hostname == groups['masters'][0]
  delegate_facts: true
  tags: validate_rke2_token

- name: Register token to all nodes for first master
  ansible.builtin.set_fact:
    rke2_token: "{{ hostvars[groups['masters'][0]]['rke2_token'] }}"
  when: inventory_hostname != groups['masters'][0]
  tags: validate_rke2_token
  
- name: Debug token for first master
  ansible.builtin.debug:
    msg: "Token for {{ inventory_hostname }}: {{ rke2_token | default('NOT SET') }}"
  tags: validate_rke2_token

# - name: Share token with all other nodes
#   ansible.builtin.set_fact:
#     rke2_token: "{{ hostvars[groups['masters'][0]]['rke2_token'] }}"
#   when: inventory_hostname != groups['masters'][0]

