---

- name: Create RKE2 installation directory for other masters
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    mode: "0755"
  become: true
  tags: install_rke2
  when: inventory_hostname in groups['masters'] and inventory_hostname != groups['masters'][0]

- name: Create RKE2 configuration file for other masters
  ansible.builtin.copy:
    content: "{{ rke2_server_config }}"
    dest: /etc/rancher/rke2/config.yaml
    mode: "0644"
  become: true
  tags: install_rke2
  when: inventory_hostname in groups['masters'] and inventory_hostname != groups['masters'][0]

- name: Install RKE2 for other masters
  ansible.builtin.shell: "curl -sfL https://get.rke2.io | sh -"
  become: true
  tags: install_rke2
  when: inventory_hostname in groups['masters'] and inventory_hostname != groups['masters'][0]

- name: Enable and start RKE2 service for other masters
  ansible.builtin.systemd:
    name: rke2-server
    state: started
    enabled: true
  when: inventory_hostname in groups['masters'] and inventory_hostname != groups['masters'][0]

- name: Link RKE2 binary to /usr/local/bin for other masters
  ansible.builtin.file:
    src: /var/lib/rancher/rke2/bin/{{ item }}
    dest: /usr/local/bin/{{ item }}
    state: link
  with_items:
    - kubectl
    - crictl
    - ctr
    - containerd
    - runc
  become: true
  tags: install_rke2
  when: inventory_hostname in groups['masters'] and inventory_hostname != groups['masters'][0]

- name: Create kubeconfig directory for other masters
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: "0755"
  become: true
  tags: install_rke2
  when: inventory_hostname in groups['masters'] and inventory_hostname != groups['masters'][0]

- name: Copy RKE2 kubeconfig to ~/.kube/config for other masters
  ansible.builtin.copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: ~/.kube/config
    mode: "0644"
    remote_src: yes
  become: true
  tags: install_rke2
  when: inventory_hostname in groups['masters'] and inventory_hostname != groups['masters'][0]

- name: Check master node is ready for other masters
  ansible.builtin.shell: |
    kubectl --kubeconfig ~/.kube/config get nodes | grep {{ inventory_hostname }} | awk '{print $2}'
  register: node_status
  until: node_status.stdout == "Ready"
  retries: 20
  delay: 15
  failed_when: node_status.rc != 0 or (node_status.retries is defined and node_status.retries == 20)
  become: true
  tags: install_rke2,validate_rke2_token
  when: inventory_hostname in groups['masters'] and inventory_hostname != groups['masters'][0]
