#cloud-config
package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg2
  - lsb-release
  - software-properties-common
  - python3
  - python3-pip
  - jq

write_files:
  - path: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    permissions: '0644'
    
  - path: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter
    permissions: '0644'

runcmd:
  # Load required kernel modules
  - modprobe overlay
  - modprobe br_netfilter
  
  # Apply sysctl settings
  - sysctl --system  

  # Disable swap
  - swapoff -a
  - sed -i '/swap/d' /etc/fstab
