---
# Kubernetes Installation Playbook
- name: Install Kubernetes with kubeadm
  hosts: masters:workers
  become: true
  gather_facts: true
  roles:
    - role: "{{ playbook_dir }}/../roles/kubernetes-install"
  
  pre_tasks:
    - name: Create temporary directory for Kubernetes
      ansible.builtin.file:
        path: "{{ playbook_dir }}/../tmp"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true
      become: false

  post_tasks:
    - name: Verify cluster status
      ansible.builtin.command: kubectl get nodes -o wide
      register: nodes_status
      changed_when: false
      delegate_to: "{{ groups['masters'][0] }}"
      run_once: true
      
    - name: Show cluster status
      ansible.builtin.debug:
        var: nodes_status.stdout_lines
      run_once: true 