---
rke2_server_config: |
  {% if inventory_hostname != groups['masters'][0] %}
  server: "https://{{ hostvars[groups['masters'][0]]['ansible_host'] }}:9345"
  token: "{{ hostvars[groups['masters'][0]]['rke2_token'] }}"
  {% endif %}
  {% if inventory_hostname in groups['masters'] %}
  tls-san:
  {% for host in groups['masters'] %}
    - "{{ hostvars[host]['ansible_host'] }}"
    - "{{ hostvars[host]['inventory_hostname'] }}"
  {% endfor %}
  node-taint:
    - "CriticalAddonsOnly=true:NoExecute"
  cni: "cilium"
  disable-cloud-controller: true
  disable: 
    - rke2-ingress-nginx
  {% endif %}
  node-ip: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
  node-name: "{{ inventory_hostname }}"
  kubelet-arg:
  - "cloud-provider=external"
  - "provider-id=openstack://{{ openstack_region }}/{{ vars[inventory_hostname + '-instance-id'] }}"